#!/bin/sh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    /usr/bin/xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    /usr/bin/xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    /usr/bin/xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
    /usr/bin/xmodmap $usermodmap
fi

# Turn off bell
xset -b

# Fix keyboard layout
setxkbmap -layout no -option ctrl:nocaps

# Fix colors
xcalib -d :0 -s 0 -v ~/.color/GCM-LENOVO-6464Y1H\(2010-05-06\).icc

# Fix some trackpoint settings
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 8 1
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 8 2
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 8 6 7 4 5

# Disable touchpad
xinput set-prop 11 "Device Enabled" 0

# Set up the screens
xrandr --output LVDS1 --mode 1280x800 --pos 0x0
# xrandr --output VGA1 --auto --pos 1280x0

# Start screenlocker
xautolock -time 10 -detectsleep -locker "i3lock -d -u -c 222222" &

# Kill stupid bluetooth
echo disable > /proc/acpi/ibm/bluetooth

emacs --daemon
dwmstatus &
exec ck-launch-session dbus-launch dwm

